# Generated by Django 5.2.5 on 2025-08-26 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whattodo', '0002_alter_task_options_alter_todolist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='priority',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this task was marked as completed', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this task was created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=1, help_text='Optional description of the task', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this task is completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Title of the task', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(help_text='The todo list this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='whattodo.todolist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this task was last updated'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this todo list was created'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the todo list', max_length=1000),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this todo list is marked as completed'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(help_text='Title of the todo list', max_length=200),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this todo list was last updated'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(help_text='The user who owns this todo list', on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['todo_list', 'created_at'], name='whattodo_ta_todo_li_2ac1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['todo_list', 'is_completed'], name='whattodo_ta_todo_li_69df68_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['todo_list', '-created_at'], name='whattodo_ta_todo_li_2c3450_idx'),
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['user', '-created_at'], name='whattodo_to_user_id_be85a5_idx'),
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['user', 'is_completed'], name='whattodo_to_user_id_c6b6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['user', '-updated_at'], name='whattodo_to_user_id_7a2feb_idx'),
        ),
    ]
