# Generated by Django 5.2.5 on 2025-08-28 01:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whattodo', '0003_alter_task_options_remove_task_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='whattodo_ta_todo_li_2ac1a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='whattodo_ta_todo_li_69df68_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='whattodo_ta_todo_li_2c3450_idx',
        ),
        migrations.RemoveIndex(
            model_name='todolist',
            name='whattodo_to_user_id_be85a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='todolist',
            name='whattodo_to_user_id_c6b6a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='todolist',
            name='whattodo_to_user_id_7a2feb_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='whattodo.todolist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
