# Generated by Django 5.2.5 on 2025-08-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whattodo', '0004_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
