# Generated by Django 5.2.5 on 2025-09-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whattodo', '0005_alter_todolist_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': (['is_completed', 'created_at'],)},
        ),
    ]
